services:
  - type: web
    name: chatbot-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production